### ISSUE TITLE
ToDo-1: Sonar-backend for Sonar 2.0 (#Influsonar)

### ISSUE THREAD

**Issue by silenus092** [rki-mf1/sonar#37]
# Sonar-backend  

## Import GenBank
- [X] Return with segmented genome information (for list-ref)
- [ ] Support segmented genome import request
- [x] Define the global accession ID because in influenza, we have multiple segments, and each segment has its accession ID.
    * We use the "strain" value in the GenBank file as the accession key. If the strain is not presented, we use the "isolated from" as the assigning value.)
- [ ] Changes the import GenBank file process for multiple Genbank files

**Note:**
1.  We assume a user provides the segments from the same strain
2. 
##  Import Sample
- [ ] Return all replicons related to reference -  Update return data for segment alignment.
thinking ...

**Note:**

##  Match profile
- [ ] Check the match query that uses the replication ID. 
thinking ...

-------
## Changes
1.  taxonomy (db_xref column in our reference table) can duplicate when we use segment genome, ----> so we change from Unique True to False......
