### ISSUE TITLE
ToDo-1:  sonar-cli for Sonar 2.0 (#Influsonar) (Major change)

### ISSUE THREAD

**Issue by silenus092** [rki-mf1/sonar#91]
We are working on testing the Sonar tool with Influenza.

We choose the Influenza A virus (A/California/07/2009(H1N1))  as our reference genome for this test.

|     As you can see, the GenBank files in NCBI. They are split by segment number   |
|---------|
|![image](https://github.com/rki-mf1/sonar/assets/8342780/d0ddbbb3-7fcc-4308-bfe4-7ed4d18bd361)|

|    Since our database schema looks like this     |
|---------|
|![image](https://github.com/rki-mf1/sonar/assets/8342780/c74a26c5-c1db-4eb2-bacc-38d42f2cc52d)|

In this case give us some concerns;
1. How do we import the GenBank file (Merge multiple GenBank files from different segments into single GenBank  ?)
2. We have to define a new accession name that references all segments because each segments have their own accession ID
    * Here's an idea:  in GenBank, we use strain value as the unique key if the strain is presented in GenBank; otherwise, we use Isolation value.

|   example record in our reference table.    |
|---------|
|![image](https://github.com/rki-mf1/sonar/assets/8342780/7c542b66-215a-4442-bb9d-15e105802533)|

3. In the "Sequence alignment process",  user needs to define the reference ID.  ([sonar-cli import -r NC_063383.1 --fasta...](URL))
   * How about aligning only one segment? 
   * What if the user provides several segments (segment number 3,4 and 5)?
   * Should we need a metafile that tells a sequence belongs to a segment number?
  

# ToDo (Major change): List updated  Jul 02 2024

### sonar-cli Import reference.
- [X] Change List-Ref display.
- [x] Tag to enable segment import and read multiple Genbank files.
- [x] Right now, we use `sonar-cli add-ref  --gb covid19.gb ` to start the import reference process. However, if we want to insert a segmented genome, we just add the multiple genbank file; `sonar-cli add-ref  --gb segment_1.gb segment_2.gb segment_3.gb –seg-ref "A/California/07/2009"`.  We assume a user uses segments from the same strain. 
     * For the accession name in the reference table, we will first look up the accession value if it is a full genome in one Genbank file. However, if not, we might use the "strain" value in the GenBank file as the accession key. If the strain is not presented, we use the "isolated from" as the assigning value.
     * In case the accession name in the reference table contains a duplicate value, we report it to the user and let the user choose to use other values, ` either isolation or strain `.
- [x] During import reference, we also construct a database for blast search (blast algorithm will sit in different script or pipeline to separate form sonar tool)

### sonar-cli Aligment,
- [x] Create another script for a similarity search. The higher score determines the winner.
  * Be careful with the reference name and ID from our database.
- [x] Assigned the segment tag to the fasta file to aid the import process in the sonar tool.
- [x] Sonar tool has the option to enable read segment property from fasta header.
- [x] Check the sonar tool again; we need to make sure it uses replicon ID to do the alignment. 
- [x] List ref output segments if available 
- [x] Align with segment id

Note:
1. First, check again that the replicon ID is actually used instead of the reference ID
2. Maybe it is a good idea to test these changes with the COVID-19 sequence and mpox first to see the problem
